[package]
name = "yom"
description = "A modern, easy to install competitor to the dash shell, built solely to execute files."
license = "MIT"
version = "0.2.3"
readme = "README.txt"
edition = "2024"
repository = "https://github.com/G0o53/yom"

keywords = ["shell", "boot", "script", "initramfs", "unix"]
categories = ["command-line-utilities", "os::linux-apis"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
shell-words = { version = "1.1.1", default-features = false }
